version: '3.8'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'steam-postgres'
    networks:
      - postgres-network
    environment:
      - POSTGRES_USER=salt
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=steamdb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    container_name: 'salt-pgadmin'
    networks:
      - postgres-network
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
networks:
  postgres-network:
    driver: bridge